<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="11.3.13" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.3.13" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.3.7" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.3.13" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.13" />
    <PackageVersion Include="CmlLib.Core" Version="4.0.6" />
    <PackageVersion Include="CmlLib.Core.Auth.Microsoft" Version="3.3.1" />
    <PackageVersion Include="CmlLib.Core.Bedrock.Auth" Version="0.0.7" />
    <PackageVersion Include="CmlLib.Core.Installer.Forge" Version="1.1.1" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="MessageBox.Avalonia" Version="3.3.1.1" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.3856.49" />
    <PackageVersion Include="XboxAuthNet.Game.Msal" Version="0.1.3" />
  </ItemGroup>
</Project>