[build-system]
requires = ["hatchling", "pyside6; sys_platform == 'win32' or sys_platform == 'linux' or sys_platform == 'darwin'"]
build-backend = "hatchling.build"

[project]
name = "X-Launcher-Core-QT"
version = "0.0.3dev"
requires-python = ">3.10"
description = "A Cross-Platform Minecraft Launcher Frontend written in Python 3 with Pyside 6"
license = "MIT"
readme = "README.md"
license-files = [ "license.md" ] 
dependencies = [
    "pyside6", 
    "requests", 
    "platformdirs"
]

[project.urls]
Repository = "https://github.com/xgui4/x-launcher"
LicenseURL = "https://opensource.org/license/mit"

[tool.hatch.build.targets.wheel.hooks.custom]
path = "hatch_build.py"

[tool.hatch.build]
artifacts = [
    "**/**_ui.py",
    "**/**_rc.py",
]

[tool.hatch.build.targets.wheel]
packages = ["src/frontend"]

[tool.pyright]
venvPath = "."
venv = ".venv"
reportAny = false
reportExplicitAny = false
reportMissingTypeStubs = false
reportImplicitRelativeImport = false

[tool.pyside6-project]
files = [
    "data/ressources.qrc",
    "src/frontend/__init__.py",
    "src/frontend/app.py",
    "src/frontend/utils/__init__.py",
    "src/frontend/ui/__init__.py",
    "src/frontend/server/__init__.py",
    "src/frontend/server/core_connector.py",
    "src/frontend/utils/__init__.py",
    "src/frontend/utils/json_trans.py",
    "src/frontend/utils/loggers.py",
    "src/frontend/utils/utils.py",
    "src/launcher.ui",
    "src/frontend/ui/sys_tray.py",
    "src/x-launcher-core.py",
    "start-x-launcher.py",
    "start-legacy.py",
    "Taskfile.yml",
    "setup.py"
]
