# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}} from task" 
    silent: true

  build:
    desc: Build the backend and prepare the pyside6 app
    cmds:
      - /usr/lib/qt6/rcc -g python "data/ressources.qrc" -o "src/frontend/ressources_rc.py" 
      - /usr/lib/qt6/uic -g python "launcher.ui" -o "src/frontend/launcher_ui.py"
      - dotnet build src/backend/X_Launcher.Core/X_Launcher.Core.csproj -c Release -o target/backend/X_Launcher.Core -f net9.0
      - dotnet build src/backend/X_Launcher.Service/X_Launcher.Service.csproj -c Release -o target/backend/X_Launcher.Service -f net9.0
      - cp src/x-launcher-core.py target/x-launcher-core.py
      - mkdir -p target/frontend
      - cp -r locales/*  target/frontend/locales/
      - cp -r src/frontend/*  target/frontend/

  build-legacy:
    desc: Build the legacy .NET versions
    cmds:
      - dotnet build src/legacy/X_Launcher.App/X_Launcher.App.csproj -c Release -o target/legacy/X_Launcher.App -f net9.0
      - dotnet build src/legacy/X_Launcher.CLI/X_Launcher.CLI.csproj -c Release -o target/legacy/X_Launcher.CLI -f net9.0 
      # - dotnet build src/legacy/X_Launcher.CLI.Windows/X_Launcher.CLI.Windows.csproj -c Release -o target/legacy/X_Launcher.CLI.Windows -f net9.0  # -> disabled by default to not working outside of Windows
      - dotnet build src/legacy/X_Launcher.Core/X_Launcher.Core.csproj -c Release -o target/legacy/X_Launcher.Core -f net9.0
      - dotnet build src/legacy/X_Launcher.Desktop/X_Launcher.Desktop.csproj -c Release -o target/legacy/X_Launcher.Desktop -f net9.0
      - cp start-legacy.py target/start-legacy.py
  debug-ui:
    desc: Run the main python-app and compiles the ui files without any other tasks
    cmds:
      - /usr/lib/qt6/rcc -g python "data/ressources.qrc" -o "src/frontend/ressources_rc.py" 
      - /usr/lib/qt6/uic -g python "about.ui" -o "src/frontend/about_ui.py"
      - /usr/lib/qt6/uic -g python "launcher.ui" -o "src/frontend/launcher_ui.py"
      - python3 src/frontend/app.py
  run:
    desc: Run the application
    depends_on: [build]
    cmds:
      - python3 target/x-launcher-core.py 
  run-legacy:
    desc: Run the legacy application
    depends_on: [build-legacy]
    cmds:
      - python3 target/start-legacy.py 

  clean:
    desc: Clean the target folder
    cmds:
      - rm -rf target/*